import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.DATABASE_URL);

const icons = {
  heart: `
...........
...........
..XX...XX..
.XXXX.XXXX.
.XXXXXXXXX.
.XXXXXXXXX.
..XXXXXXX..
...XXXXX...
....XXX....
.....X.....
...........`,
  "arrow-right": `
...........
...........
......X....
.......X...
........X..
.XXXXXXXXX.
........X..
.......X...
......X....
...........
...........`,
  check: `
...........
...........
...........
.........X.
........X..
.X.....X...
..X...X....
...X.X.....
....X......
...........
...........`,
  plus: `
...........
.....X.....
.....X.....
.....X.....
.....X.....
.XXXXXXXXX.
.....X.....
.....X.....
.....X.....
.....X.....
...........`,
  home: `
...........
.....X.....
....X.X....
...X...X...
..X.....X..
.X.......X.
..X.....X..
..X.XXX.X..
..X.X.X.X..
..XXX.XXX..
...........`,
  smile: `
...........
...XXXXX...
..X.....X..
.X.......X.
.X..X.X..X.
.X.......X.
.X.X...X.X.
.X..XXX..X.
..X.....X..
...XXXXX...
...........`,
};

const [{ count }] = await sql`SELECT count(*)::int AS count FROM icons`;
if (count > 0) {
  console.log(`Table already has ${count} icons, skipping seed.`);
} else {
  for (const [name, art] of Object.entries(icons)) {
    const pixels = art.replace(/\s/g, "").replace(/X/g, "1").replace(/\./g, "0");
    if (pixels.length !== 121) throw new Error(`${name}: ${pixels.length} cells`);
    await sql`INSERT INTO icons (name, pixels, status) VALUES (${name}, ${pixels}, 'validated')`;
  }
  console.log(`Seeded ${Object.keys(icons).length} icons.`);
}
